name: lekpad
description: A standard Balochi keyboard named Lekpad with Balorabi and Balotin support.
version: 1.0.0+1

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0 # Standard free font loader for "Amiri" and others

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # If you prefer to download and include the Amiri font files offline,
  # download "Amiri-Regular.ttf" and "Amiri-Bold.ttf" from Google Fonts,
  # place them in an "assets/fonts/" folder, and uncomment the section below:
  #
  # fonts:
  #   - family: Amiri
  #     fonts:
  #       - asset: assets/fonts/Amiri-Regular.ttf
  #       - asset: assets/fonts/Amiri-Bold.ttf
  #         weight: 700
