name: Lekpad
description: A standard Balochi keyboard named Lekpad with Balorabi and Balotin support.
version: 1.0.0+8

publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0 # Standard free font loader for "Amiri" and others
  shared_preferences: ^2.2.2 # For saving customizable theme colors securely to share with Android/iOS keyboard

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Asset declaration to load and display the Lekpad transparent app logo inside the Flutter app!
  assets:
    - images/icon.png
